### ISSUE TITLE
better way to serverping

### ISSUE THREAD

**Issue by shugen002** [BossShop/BossShop#17]
well , I found this:
https://www.spigotmc.org/threads/the-bungee-bukkit-plugin-messaging-channel.499/

in this topic , I found we can get server player status through the bungee plugin messaging channel.
So i think that even if we can ' t get motd in this way , to get current player in this way is better to direct connect to the server.
because through this way , we don't need to create any socket just use the ready-made .
it will save many resource .

maybe provide different mode for user to choose is better.

**Comment by confuser** [comment]
The problem with this is, we're then limiting this to Bungeecord only proxies. The current way is far more flexible in supporting other systems such as LilyPad. Pinging a Minecraft server requires very few resources and will have no impact on your minecraft server's performance.
